# Configuration for welcome - https://github.com/behaviorbot/welcome

newIssueWelcomeComment: >
  ğŸ‘‹ Thanks for opening your first issue here!

    We're glad to have you with us!

newPRWelcomeComment: >
  ğŸ‰ Thanks for your first pull request â€” we really appreciate it!  
  
  Welcome aboard! ğŸš€

firstPRMergeComment: >
  ğŸ¥³ Congrats on your first merged PR!  
  
  Thanks for contributing and helping make this project better ğŸ’ª 
